export { default as chunk } from './Array/chunk/index'
export { default as compact } from './Array/compact/index'
export { default as difference } from './Array/difference/index'
export { default as intersection } from './Array/intersection/index'
export { default as debounce } from './fn/debounce'
export { default as throttle } from './fn/throttle'
